export enum ConfigKeys {
  APP_PORT = 'APP_PORT',
  APP_HOST = 'APP_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DATABASE = 'DATABASE',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  JWT_SECRET = 'JWT_SECRET',
  BASE_URL = 'BASE_URL',
}